### ISSUE TITLE
Call to undefined method is_wanted in lib/wupee/notifier.rb

### ISSUE THREAD

**Issue by nicolasconnault** [sleede/wupee#12]
Line 66 needs to be changed from 
```ruby
notification.is_wanted = false unless send_notification?(receiver, @notification_type)
```
to 
```ruby
send_notification?(receiver, @notification_type)
```

**Comment by nflorentin** [comment]
Hi!

thanks for your report but can you give more details ? 

Why do you want to remove `notification.is_wanted = false` ?

**Comment by nicolasconnault** [comment]
Because in your current Dev branch (2.0.0.beta) this method (is_wanted=)
doesn't exist :)

**Comment by nflorentin** [comment]
It's been a while.. it's possible that I am missing something but I can see in this migration the column is_wanted : https://github.com/sleede/wupee/blob/v2.0.0.beta2/db/migrate/20151029113107_create_wupee_notifications.rb

**Comment by nicolasconnault** [comment]
Oh I think I know what's happened. I first installed the 1.4 gem, then the
2.0 one, but didn't run the migration the second time so that column is
missing. Good call, thanks for your quick reply!

**Comment by nflorentin** [comment]
You're welcome!
