### ISSUE TITLE
Missing actor of the notification

### ISSUE THREAD

**Issue by ramoncaldeira** [sleede/wupee#2]
Hi!

I would like to have an in-app notification like the following:
User A mentioned you on Video A.

"you" would be my receiver
"Video A" or "User A" would be attached objects... It is possible to attach multiple objects?

I think "Video A" should be an attached object and "User A" should fall in another abstraction, for example an Actor

**Comment by nflorentin** [comment]
Hi and thanks you for your interest !

I think that attaching a notification to various objects isn't a good idea and that if you have to do it, it means that you are trying to achieve a goal that doesn't fit well a notification system.

I think that the goal you are trying to achieve is more an activity feed like github activity feed and you should use a gem like [public_activity](https://github.com/chaps-io/public_activity).

By using both gems, you could create activities (ex: User A mentioned You on Video A) with public_activity and create a notification attaching the activity to it.

**Comment by ramoncaldeira** [comment]
Good point, I could attach an Public Activity object as an attachable object into my Wupee:Notification object. But I think it would bring a lot of redundancy. Activity and Notification objects are pretty similar and I wouldn't need anything from Public Activity but its polymorphic association of owner. 

That said, I could still create my own Activity model associating a generic actor with a generic object and use it as an attachable object from my Notification. It would do for my usecase but the Activity object wouldn't have an isolated meaning. In the mention case, for example, the activity would need the notification's recipient in order to make sense. I could also add a recipient in my Activity model but that would lead to duplication.

I still find an polymorphic actor on the notification model a simpler and cleaner solution for the usecase.
