### ISSUE TITLE
current_user

### ISSUE THREAD

**Issue by pablodgcatulo** [sleede/wupee#9]
Hi, Grate awesome here! I'm just having an issue with the current_user method. I defined it on my main app application controller ....but it just keep ignoring me :( . I'm using rails 5.0.1 and devise. My current_user method is aliased as current_usuario by devise.

Could you please update the readme on how or where you expect to define it? 

Thanks!

**Comment by nflorentin** [comment]
Hi, 

thanks for your interest ! 

I'm always using wupee with devise as authentication system and I didn't have problem as devise already define this method. I mean I never had to define it. Could you please give me more details about "it just keep ignoring me" ?

As a side note, the gem only requires this method to be defined if you use the json API to fetch the notifications.

You're welcome.

**Comment by pablodgcatulo** [comment]
Hi! Thank you for your gem. I know. I just wanted to test all before using it. The error i'm getting is  that current_user is not defined. The error is thrown (obviously) at [https://github.com/sleede/wupee/blob/master/app/controllers/wupee/api/notifications_controller.rb#L9](https://github.com/sleede/wupee/blob/master/app/controllers/wupee/api/notifications_controller.rb#L9)

in my main app aplication controller just define it as 
```ruby
def current_user
  current_usuario
end
```
I forgot to tell you that I'm using v 1.1.4. Thanks again!

**Comment by nflorentin** [comment]
Hi !

Sorry! I was wrong, thinking it again makes me realize that actually you're right, this cannot works because the engine uses Wupee/ApplicationController#current_user method and cannot see the current_user method defined in ApplicationController of the app. 

The json API was pretty experimental... I'd advice you to implements your own as every app has specific needs.

Also, I strongly recommend you to use [the version 2.0.0.beta1](https://rubygems.org/gems/wupee/versions/2.0.0.beta1) as there are breakings changes between the two versions. 

Thanks for you interest!

**Comment by pablodgcatulo** [comment]
Thanks Nicolas. I'm using it anyway (just the models). Maybe it would be a good idea to add the 'current_user' call as a parameter ( notifications gem do so https://github.com/rails-engine/notifications). I also have a deprecation warning for rails 5.1. I can create those PR request for wupee. Do you think it's a good idea to include them in the beta1? 

Oh by the way, remember to tag the 2.0.0 beta1 in github :relaxed:

**Comment by nflorentin** [comment]
Hi Pablo,

Thanks for the example of rails-engine/notifications :) This could do the trick.
Also thank for reminding me, I just created the tag 2.0.0.beta1.

I'd appreciate your PR sure! I just merged the branch (remove-notif-config) of 2.0.0 beta1
on master so you can create your PRs and submit them. 

thanks for your help !
